name: docker_image_build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image to download (e.g., nginx:latest)"
        required: true
        default: "rasa:3.6.21"
      cleanup:
        description: "Whether to clean up disk space (true or false)"
        required: true
        default: "false"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.cleanup == 'true' }}
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: prepare Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM python:3.9-slim
          
          WORKDIR /workspace
      
          RUN apt install rustc \
              && apt install cargo \
              && pip install --upgrade pip \
              && pip install rasa[full]
      
          CMD ["bash"]
          EOF

      - name: generate filename
        id: filename
        run: |
          SAFE_NAME=$(echo "${{ inputs.image }}" | sed 's/[\/:]/_/g')
          echo "SAFE_NAME=${SAFE_NAME}" >> $GITHUB_ENV

      - name: build Dockerfile
        run: |
          docker build -t ${{ inputs.image }} .

      - name: save image
        run: |
          docker save ${{ inputs.image }} > ${{ runner.temp }}/${{ env.SAFE_NAME }}.tar

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SAFE_NAME }}
          path: ${{ runner.temp }}/${{ env.SAFE_NAME }}.tar
